---
output: # rmarkdown::github_document
  html_document:
  pdf_document: default
  word_document: default
title: "Assignment 9. One-sample tests vs. Two-sample tests" 
---

Work individually. Put your answer on a Word document. Screenshots Minitab for the results of the tests.

1. Form three 1-sample hypotheses and three 2-sample hypotheses from **dataset 1**. Write your H1 hypotheses. Report p-value and your conclusion. 

2. Form two 95% confidence intervals from **dataset 1**.

3. Form three 1-sample hypotheses and three 2-sample hypotheses from **dataset 2**. Write your H1 hypotheses. Report p-value and your conclusion. 

4. Form two 95% confidence intervals from **dataset 2**.


-------
-------

Dataset 1 Description: 

[Download](student-mat.csv)

The data were obtained in a survey of students math and portuguese language courses in secondary school. It contains a lot of interesting social, gender and study information about students. The data has been modified for educational purpose. Suppose that the dataset is a random sample from a population of secondary school students. 

Content:
Attributes for both student-mat.csv (Math course) and student-por.csv (Portuguese language course) datasets:

- school - student's school (binary: 'GP' - Gabriel Pereira or 'MS' - Mousinho da Silveira)
- sex - student's sex (binary: 'F' - female or 'M' - male)
- age - student's age (numeric: from 15 to 22)
- address - student's home address type (binary: 'U' - urban or 'R' - rural)
- famsize - family size (binary: 'LE3' - less or equal to 3 or 'GT3' - greater than 3)
- Pstatus - parent's cohabitation status (binary: 'T' - living together or 'A' - apart)
- Medu - mother's education (numeric: 0 - none, 1 - primary education (4th grade), 2 – 5th to 9th grade, 3 – secondary - education or 4 – higher education)
- Fedu - father's education (numeric: 0 - none, 1 - primary education (4th grade), 2 – 5th to 9th grade, 3 – secondary education or 4 – higher education)
- Mjob - mother's job (nominal: 'teacher', 'health' care related, civil 'services' (e.g. administrative or police), 'at_home' or 'other')
- Fjob - father's job (nominal: 'teacher', 'health' care related, civil 'services' (e.g. administrative or police), 'at_home' or 'other')
- reason - reason to choose this school (nominal: close to 'home', school 'reputation', 'course' preference or 'other')
- guardian - student's guardian (nominal: 'mother', 'father' or 'other')
- traveltime - home to school travel time (hours)
- studytime - daily study time (hours)
- failures - number of past class failures (numeric: n if 1<=n<3, else 4)
- schoolsup - extra educational support (binary: yes or no)
- famsup - family educational support (binary: yes or no)
- paid - extra paid classes within the course subject (Math or Portuguese) (binary: yes or no)
- activities - extra-curricular activities (binary: yes or no)
- nursery - attended nursery school (binary: yes or no)
- higher - wants to take higher education (binary: yes or no)
- internet - Internet access at home (binary: yes or no)
- romantic - with a romantic relationship (binary: yes or no)
- famrel - quality of family relationships (numeric: from 1 - very bad to 5 - excellent)
- freetime - free time after school (numeric: from 1 - very low to 5 - very high)
- goout - going out with friends (numeric: from 1 - very low to 5 - very high)
- Dalc - workday alcohol consumption (numeric: from 1 - very low to 5 - very high)
- Walc - weekend alcohol consumption (numeric: from 1 - very low to 5 - very high)
- health - current health status (numeric: from 1 - very bad to 5 - very good)
- absences - number of school absences (numeric: from 0 to 93)
- The grades are related with the course subject, Math or Portuguese:

-------
-------

Dataset 2 Description: 

Suppose that the below data is a random sample from a population of college students in Indonesia. 

[Download](college.csv)

- type_school: Type of school that student attends

- school_accreditation: Quality of school. A is better than B.

- gender: Gender of student

- interest: How interested are students if they go to college

- residence: Type of residence

- parent_age: Parent age

- parent_salary: Parent salary per month in IDR/Rupiah

- house_area: Parent house area in meter square

- average_grades: Average of grades in scale of 0-100

- parent_was_in_college: Was parent ever in college?
