---
output: # rmarkdown::github_document
  html_document:
  pdf_document: default
  word_document: default
title: "Assignment 8. Two-Sample Tests" 
---

Work individually. Put your answer on a Word document. Write the test conclusion and screenshots Minitab for the results of the tests. Submit to Canvas for credits. Screenshots Minitab for the results of the tests.

The answers for questions 1 to 3 can be found at this link: [Answers](https://bryant.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=5142b74a-1547-4865-b06d-afb70151ddae)

You just need to do question 4 and follow the above instruction to submit. 

[This data](student-mat.csv) were obtained in a survey of students math and portuguese language courses in secondary school. Assume that the data is a random sample of secondary school students. Screenshots Minitab for the results of the tests.

1. Test if there is a difference in number of studying hours (studytime) between male and female students in secondary school. Report the p-value and your conclusion. Screenshots Minitab for the results of the tests.

2. Test if female students study more hours than male students in secondary school. Report the p-value and your conclusion. Screenshots Minitab for the results of the tests.

3. Test if the students who have access to Internet at home have a higher final grade than those who do not. Report the p-value and your conclusion. Screenshots Minitab for the results of the tests.

4. Form two hypotheses comparing two groups and test for them. Write your H1 hypotheses. Report the p-value and your conclusion. Screenshots Minitab for the results of the tests.

---

Data Description: 

[Download](student-mat.csv)

The data were obtained in a survey of students math and portuguese language courses in secondary school. It contains a lot of interesting social, gender and study information about students. The data has been modified for educational purpose. 

Content:
Attributes for both student-mat.csv (Math course) and student-por.csv (Portuguese language course) datasets:

- school - student's school (binary: 'GP' - Gabriel Pereira or 'MS' - Mousinho da Silveira)
- sex - student's sex (binary: 'F' - female or 'M' - male)
- age - student's age (numeric: from 15 to 22)
- address - student's home address type (binary: 'U' - urban or 'R' - rural)
- famsize - family size (binary: 'LE3' - less or equal to 3 or 'GT3' - greater than 3)
- Pstatus - parent's cohabitation status (binary: 'T' - living together or 'A' - apart)
- Medu - mother's education (numeric: 0 - none, 1 - primary education (4th grade), 2 – 5th to 9th grade, 3 – secondary - education or 4 – higher education)
- Fedu - father's education (numeric: 0 - none, 1 - primary education (4th grade), 2 – 5th to 9th grade, 3 – secondary education or 4 – higher education)
- Mjob - mother's job (nominal: 'teacher', 'health' care related, civil 'services' (e.g. administrative or police), 'at_home' or 'other')
- Fjob - father's job (nominal: 'teacher', 'health' care related, civil 'services' (e.g. administrative or police), 'at_home' or 'other')
- reason - reason to choose this school (nominal: close to 'home', school 'reputation', 'course' preference or 'other')
- guardian - student's guardian (nominal: 'mother', 'father' or 'other')
- traveltime - home to school travel time (numeric: 1 - <15 min., 2 - 15 to 30 min., 3 - 30 min. to 1 hour, or 4 - >1 hour)
- studytime - daily study time (hours)
- failures - number of past class failures (numeric: n if 1<=n<3, else 4)
- schoolsup - extra educational support (binary: yes or no)
- famsup - family educational support (binary: yes or no)
- paid - extra paid classes within the course subject (Math or Portuguese) (binary: yes or no)
- activities - extra-curricular activities (binary: yes or no)
- nursery - attended nursery school (binary: yes or no)
- higher - wants to take higher education (binary: yes or no)
- internet - Internet access at home (binary: yes or no)
- romantic - with a romantic relationship (binary: yes or no)
- famrel - quality of family relationships (numeric: from 1 - very bad to 5 - excellent)
- freetime - free time after school (numeric: from 1 - very low to 5 - very high)
- goout - going out with friends (numeric: from 1 - very low to 5 - very high)
- Dalc - workday alcohol consumption (numeric: from 1 - very low to 5 - very high)
- Walc - weekend alcohol consumption (numeric: from 1 - very low to 5 - very high)
- health - current health status (numeric: from 1 - very bad to 5 - very good)
- absences - number of school absences (numeric: from 0 to 93)
- The grades are related with the course subject, Math or Portuguese:
